// data.js — JoelDroid Mods YT
// Generado: 2026-04-23T00:00:00.000Z
// Carga instantánea sin Firebase ni Gist
// ─────────────────────────────────────────────────────────────────
// INSTRUCCIONES:
//   1. Sube este archivo al mismo directorio que index.html en GitHub Pages
//   2. Para agregar/editar juegos: usa el Panel de Control → "Descargar data.js"
//      y reemplaza este archivo con el nuevo generado
// ─────────────────────────────────────────────────────────────────

window.JUEGOS_DATA = [
  {
    "id": "global-truck-online",
    "name": "Global Truck Online",
    "description": "El simulador de camiones más avanzado con multijugador masivo. Desarrollado por JoelDroid Labs y modificado para ofrecer la mejor experiencia premium. Maneja rutas internacionales, gestiona tu flota y domina las carreteras del mundo.",
    "thumb": "https://play-lh.googleusercontent.com/JJiHxM3IMImgKaROZ3U6yivclo5jxepBfZRShfCoxij7SrY233VKi_sp0YoxiWyHSfttjrgfYAy2vDVtYiaU5dw=w240-h480-rw",
    "ver": "v1.5.2",
    "size": "420 MB",
    "visible": true,
    "homeButtonVisible": true,
    "homeButtonText": "Descargar APK",
    "homeButtonColor": "blue",
    "homeButtonColorKey": "blue",
    "downloadButtonText1": "Descargar Mod 1",
    "downloadButtonLink1": "#",
    "downloadButtonVisible1": true,
    "downloadButtonColor1": "#3b82f6",
    "downloadButtonText2": "Descargar Mod 2",
    "downloadButtonLink2": "#",
    "downloadButtonVisible2": true,
    "downloadButtonColor2": "#3b82f6",
    "modBadgeText": "MOD APP",
    "modBadgeBgColor": "#ef4444",
    "modBadgeBgColorKey": "red",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeBgColor": "#10b981",
    "updateBadgeBgColorKey": "green",
    "updateBadgeVisible": true,
    "features": ["Monedas Infinitas", "Sin Anuncios", "Todo Desbloqueado"],
    "warningVisible": true,
    "warningText": "Si el juego presenta problemas al instalar, asegúrate de desinstalar cualquier versión previa de la Google Play Store para evitar conflictos.",
    "downloadNameSecondary": "GLOBAL TRUCK ONLINE MOD APP",
    "visits": 1250,
    "timestamp": 1716220800000,
    "order": 0
  },
  {
    "id": "trucker-of-europe-3",
    "name": "Trucker of Europe 3",
    "description": "Una obra maestra de la conducción pesada. Modificado especialmente para entusiastas que buscan desbloquear todo el potencial de la gestión de carga. Rutas por toda Europa con física realista.",
    "thumb": "https://play-lh.googleusercontent.com/hOBKTdAPqpMPdWqg5EUCTlJqXwQDf5l9L_cK7IDJRqiEb9E6M6IuHxLPpVSGBHxBkA=w240-h480-rw",
    "ver": "v0.40.1",
    "size": "315 MB",
    "visible": true,
    "homeButtonVisible": true,
    "homeButtonText": "Descargar APK",
    "homeButtonColor": "blue",
    "homeButtonColorKey": "blue",
    "downloadButtonText1": "Descargar Mod 1",
    "downloadButtonLink1": "#",
    "downloadButtonVisible1": true,
    "downloadButtonColor1": "#3b82f6",
    "downloadButtonText2": "Descargar Mod 2",
    "downloadButtonLink2": "#",
    "downloadButtonVisible2": true,
    "downloadButtonColor2": "#3b82f6",
    "modBadgeText": "MOD APP",
    "modBadgeBgColor": "#ef4444",
    "modBadgeBgColorKey": "red",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeBgColor": "#10b981",
    "updateBadgeBgColorKey": "green",
    "updateBadgeVisible": false,
    "features": ["Monedas Infinitas", "Sin Anuncios", "Sin Virus"],
    "warningVisible": true,
    "warningText": "Si el juego presenta problemas al instalar, asegúrate de desinstalar cualquier versión previa de la Google Play Store para evitar conflictos.",
    "downloadNameSecondary": "TRUCKER OF EUROPE MOD APP",
    "visits": 890,
    "timestamp": 1704844800000,
    "order": 1
  },
  {
    "id": "bus-simulator-ultimate",
    "name": "Bus Simulator Ultimate",
    "description": "Conduce autobuses por rutas reales de todo el mundo. Versión MOD con dinero ilimitado y todas las rutas desbloqueadas desde el inicio. El simulador de buses más realista para Android.",
    "thumb": "https://play-lh.googleusercontent.com/pDMYl5eeU9RHmFgJVctqmT5SnZd3bKOq_Q5Z5QVbm5VWKJ9Q5E2IvKllWjWPVmCHug=w240-h480-rw",
    "ver": "v2.1.7",
    "size": "380 MB",
    "visible": true,
    "homeButtonVisible": true,
    "homeButtonText": "Descargar APK",
    "homeButtonColor": "blue",
    "homeButtonColorKey": "blue",
    "downloadButtonText1": "Descargar Mod APK",
    "downloadButtonLink1": "#",
    "downloadButtonVisible1": true,
    "downloadButtonColor1": "#3b82f6",
    "downloadButtonText2": "",
    "downloadButtonLink2": "",
    "downloadButtonVisible2": false,
    "downloadButtonColor2": "#3b82f6",
    "modBadgeText": "MOD",
    "modBadgeBgColor": "#ef4444",
    "modBadgeBgColorKey": "red",
    "modBadgeVisible": true,
    "updateBadgeText": "NEW",
    "updateBadgeBgColor": "#10b981",
    "updateBadgeBgColorKey": "green",
    "updateBadgeVisible": true,
    "features": ["Dinero Ilimitado", "Rutas Desbloqueadas", "Sin Anuncios"],
    "warningVisible": false,
    "warningText": "",
    "downloadNameSecondary": "BUS SIMULATOR ULTIMATE MOD",
    "visits": 2100,
    "timestamp": 1745000000000,
    "order": 2
  },
  {
    "id": "euro-truck-driver",
    "name": "Euro Truck Driver",
    "description": "Recorre las carreteras de Europa al volante de los camiones más potentes. MOD con combustible infinito, todo desbloqueado y sin restricciones de velocidad. Experiencia de conducción definitiva.",
    "thumb": "https://play-lh.googleusercontent.com/8UtfBwp5L9j3lFLumRlXpPpPW6tV3vfmqOlWMPJMklz6QVQB15A7D7n4OU1-W0WIGA=w240-h480-rw",
    "ver": "v4.2",
    "size": "290 MB",
    "visible": true,
    "homeButtonVisible": true,
    "homeButtonText": "Descargar APK",
    "homeButtonColor": "blue",
    "homeButtonColorKey": "blue",
    "downloadButtonText1": "Descargar Mod APK",
    "downloadButtonLink1": "#",
    "downloadButtonVisible1": true,
    "downloadButtonColor1": "#3b82f6",
    "downloadButtonText2": "",
    "downloadButtonLink2": "",
    "downloadButtonVisible2": false,
    "downloadButtonColor2": "#3b82f6",
    "modBadgeText": "MOD",
    "modBadgeBgColor": "#3b82f6",
    "modBadgeBgColorKey": "blue",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeBgColor": "#10b981",
    "updateBadgeBgColorKey": "green",
    "updateBadgeVisible": false,
    "features": ["Combustible Infinito", "Todo Desbloqueado", "Premium"],
    "warningVisible": false,
    "warningText": "",
    "downloadNameSecondary": "EURO TRUCK DRIVER MOD",
    "visits": 750,
    "timestamp": 1712000000000,
    "order": 3
  },
  {
    "id": "truck-simulator-pro",
    "name": "Truck Simulator PRO 2016",
    "description": "El clásico simulador de camiones con gráficos mejorados y física de conducción avanzada. MOD desbloqueado con todos los vehículos disponibles desde el principio sin necesidad de dinero.",
    "thumb": "https://play-lh.googleusercontent.com/AzJAQqEHarYqBbYRJJxf_3fHWQ63K1g97E1bkO7eqmS3H9CGRLJfP7UzMp-Gvrl-fQ=w240-h480-rw",
    "ver": "v1.8",
    "size": "450 MB",
    "visible": true,
    "homeButtonVisible": true,
    "homeButtonText": "Descargar APK",
    "homeButtonColor": "blue",
    "homeButtonColorKey": "blue",
    "downloadButtonText1": "Descargar Mod APK",
    "downloadButtonLink1": "#",
    "downloadButtonVisible1": true,
    "downloadButtonColor1": "#3b82f6",
    "downloadButtonText2": "",
    "downloadButtonLink2": "",
    "downloadButtonVisible2": false,
    "downloadButtonColor2": "#3b82f6",
    "modBadgeText": "MOD PRO",
    "modBadgeBgColor": "#8b5cf6",
    "modBadgeBgColorKey": "purple",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeBgColor": "#10b981",
    "updateBadgeBgColorKey": "green",
    "updateBadgeVisible": false,
    "features": ["Todos los Vehículos", "Mapas Desbloqueados", "Sin Anuncios"],
    "warningVisible": false,
    "warningText": "",
    "downloadNameSecondary": "TRUCK SIMULATOR PRO MOD",
    "visits": 620,
    "timestamp": 1700000000000,
    "order": 4
  },
  {
    "id": "grand-truck-simulator",
    "name": "Grand Truck Simulator 2",
    "description": "Simula la vida real de un camionero brasileño con entregas, rutas y gestión de flota. MOD con dinero infinito, combustible ilimitado y todo el contenido premium desbloqueado.",
    "thumb": "https://play-lh.googleusercontent.com/Z9k4XN7Ht7I9Ml6b3u0Y1RFQN2YnFfnXuVIzFq3bKj7WlNxWs5WJqU5AqBKBOKvA=w240-h480-rw",
    "ver": "v1.0.34f3",
    "size": "335 MB",
    "visible": true,
    "homeButtonVisible": true,
    "homeButtonText": "Descargar APK",
    "homeButtonColor": "blue",
    "homeButtonColorKey": "blue",
    "downloadButtonText1": "Descargar Mod APK",
    "downloadButtonLink1": "#",
    "downloadButtonVisible1": true,
    "downloadButtonColor1": "#3b82f6",
    "downloadButtonText2": "",
    "downloadButtonLink2": "",
    "downloadButtonVisible2": false,
    "downloadButtonColor2": "#3b82f6",
    "modBadgeText": "MOD",
    "modBadgeBgColor": "#ef4444",
    "modBadgeBgColorKey": "red",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeBgColor": "#10b981",
    "updateBadgeBgColorKey": "green",
    "updateBadgeVisible": true,
    "features": ["Dinero Infinito", "Combustible Ilimitado", "Premium"],
    "warningVisible": true,
    "warningText": "Desinstala la versión oficial antes de instalar este MOD para evitar conflictos.",
    "downloadNameSecondary": "GRAND TRUCK SIMULATOR 2 MOD",
    "visits": 410,
    "timestamp": 1740000000000,
    "order": 5
  }
];

// ── Señal para index.html ──────────────────────────────────────
window.__JD_DATA_READY = true;

// ── Auto-render si index.html ya cargó __JD_RENDER ────────────
if (typeof window.__JD_RENDER === 'function' && !window.__JD_DONE) {
  window.__JD_RENDER(window.JUEGOS_DATA);
}
