/* ================================================================
   juegos_data.js — JoelDroid Mods YT
   Generado: 2026-04-23T01:22:04Z
   Juegos: 20
   
   Este archivo se actualiza automáticamente desde el Panel de Control
   cada vez que guardas o eliminas un juego.
   NO editar manualmente.
   ================================================================ */

/* ── CATÁLOGO PRINCIPAL (sin thumbs, 26KB, carga instantánea) ── */
const JUEGOS_DATA = [
  {
    "id": "uWeUJYbJhCcmjImQ3jEB",
    "name": "Car Parking Multiplayer 2",
    "description": "Juego de aparcamiento con modo multijugador y coches tuneados. Modo multijugador de mundo abierto, tuneado de coches, ¡carreras!",
    "ver": "V1.3.1.3",
    "size": "2.96 GB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/kpx8m52wwsyh5jv/Car_Parking_Multiplayer_2_v1.3.1.3_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/kpx8m52wwsyh5jv/Car_Parking_Multiplayer_2_v1.3.1.3_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Monedas Infinitas",
      "Coches paga liberado",
      "Garaje 2 Liberado",
      "Compras gratis",
      "Online Multiplayer Funcinal",
      "Sin Anuncios"
    ],
    "timestamp": 1776894177640,
    "order": 15,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "ms8TbhI81zTMsRZVfTzm",
    "name": "Moto Wheelie 3D",
    "description": "¡Un juego de caballito como nunca antes visto! Juego inspirado en motos del mundo real. Conduce motos haciendo caballitos, acrobacias, corte de giro, drift, burnout, etc. Los modos de entrega, desafío y carrera también están disponibles.",
    "ver": "V0.105",
    "size": "99 MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/z9rf0dkaib6xqic/Moto_Wheelie_3D_v0.105_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/z9rf0dkaib6xqic/Moto_Wheelie_3D_v0.105_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Todo liberado",
      "Sin Anuncios"
    ],
    "timestamp": 1776894168047,
    "order": 18,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "02qE0OihFc0ksBiW4pUT",
    "name": "Car Parking Multiplayer",
    "description": "Juego de mundo abierto con modo multijugador y Tuning Cars. Más que solo estacionamiento: modo multijugador de mundo abierto, tuning de autos, ¡caminar libremente!",
    "ver": "V4.9.8",
    "size": "1.86 GB",
    "visible": true,
    "modBadgeText": "MOD MENU",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/1ct5qgk6rgsz1j6/Car_Parking_Multiplayer_v4.9.8_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/1ct5qgk6rgsz1j6/Car_Parking_Multiplayer_v4.9.8_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Monedas Infinitas",
      "Coches Vip liberados",
      "Mansiones liberados",
      "Rines",
      "Motor W16",
      "Sirenas",
      "Claxon",
      "Online Multiplayer"
    ],
    "timestamp": 1776894156174,
    "order": 18,
    "visits": 1,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "LC7P1fxJX3MRMY0g1QB0",
    "name": "Hungry Shark  World",
    "description": "¡Sumérgete en el juego oficial de la Shark Week con Hungry Shark Evolution! Conviértete en el depredador supremo es este juego de tiburones que no necesita Internet. Domina el océano y devora todo a tu paso en esta aventura en un mundo submarino 🦈🦈🦈🦈",
    "ver": "V7.7.1",
    "size": "227 MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/ht7gjf8znf7nycc/Hungry_Shark_World_v7.7.1_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/ht7gjf8znf7nycc/Hungry_Shark_World_v7.7.1_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Monedas Infinitos",
      "Gemas infinitos",
      "tokens infinitos",
      "Sin anuncios",
      "Todo liberado"
    ],
    "timestamp": 1776894068235,
    "order": 17,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "sHBaQ4jxKB7AQhsjPsLJ",
    "name": "Off The Road",
    "description": "¡Hola, todoterrenos! ¡Ya está aquí el nuevo simulador de conducción todoterreno de mundo abierto! ¡Es hora de salir de la carretera!",
    "ver": "V1. 18.2",
    "size": "539 MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/sly68pnfeeug1fw/Off_The_Road_v1.18.2_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/sly68pnfeeug1fw/Off_The_Road_v1.18.2_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Monedas Infinitas",
      "Nivel 999",
      "Vehículos VIP Liberados",
      "Eres Miembro VIP",
      "Sin Anuncios"
    ],
    "timestamp": 1776894060618,
    "order": 17,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "MycxFXUXAoQwUx7GMXd2",
    "name": "Truck Simulator PRO US",
    "description": "¡Conduce camiones potentes por los Estados Unidos! ¡Experimenta la emoción del transporte de mercancías en Truck Simulation PRO USA! ",
    "ver": "V1. 46",
    "size": "1.42 GB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/w02r9zjz4xyw7em/Truck_PRO_USA_v1.46_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/w02r9zjz4xyw7em/Truck_PRO_USA_v1.46_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Monedas Infinitos",
      "Diamantes Infinitos",
      "Tokens map infinito",
      "Nivel XP 60",
      "Sin Anuncios"
    ],
    "timestamp": 1776894049837,
    "order": 17,
    "visits": 1,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "8OajZpH1fJX3mPNo1iqF",
    "name": "Bus Simulator Ultimate",
    "description": "Bus Simulator : Ultimate\n ¡El camino es tuyo, el volante está en tus manos!  Experimenta una simulación única con gráficos realistas, modelado urbano detallado y autobuses con licencia oficial. Ponte al volante de gigantes de la industria como Mercedes-Benz, Temsa, Setra, Scania y Marcopolo, ofreciendo un servicio de pasajeros de primera clase en largas distancias.",
    "ver": "V 2.2.8",
    "size": "1.6 GB",
    "visible": true,
    "modBadgeText": "MOD APP",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/x1iif9vybcpti7j/Bus_Simulator_Ultimate_v2.2.8_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/x1iif9vybcpti7j/Bus_Simulator_Ultimate_v2.2.8_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Monedas Infinitas",
      "Comprás Gratis",
      "Sin Anuncios"
    ],
    "timestamp": 1776894038439,
    "order": 17,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "3aurnrdnBWV8JUy1PlRk",
    "name": "DRIVERS JOBS ONLINE SIMULATOR",
    "description": "Drivers Jobs Online Simulator es un juego de simulación de vehículos en línea en el que puedes trabajar como conductor de varios tipos de vehículos.",
    "ver": "V0.192",
    "size": "1,2GB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/5fala5bll92633o/Drivers_Jobs_Online_v0.192_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/5fala5bll92633o/Drivers_Jobs_Online_v0.192_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Nivel XP 50",
      "Vehículos paga liberado",
      "Online Multiplayer",
      "Velocidad Speed",
      "Sin Anuncios"
    ],
    "timestamp": 1776894013649,
    "order": 18,
    "visits": 0,
    "warningVisible": false,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "LwoLXfJV5dYt96ipaSYB",
    "name": "Truck Simulator BigRigs",
    "description": "Conduce diversos tipos de camiones con múltiples configuraciones de chasis, así como camiones rígidos con física realista.\nCompra garajes, camiones y remolques y expande tu imperio camionero.",
    "ver": "V1. 5.7",
    "size": "970 MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/x92gg45yq1g7sob/Truck_Simulator_Big_Rigs_v1.5.7_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/x92gg45yq1g7sob/Truck_Simulator_Big_Rigs_v1.5.7_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Nivel XP 600",
      "Garajes liberados",
      "Grifos desbloqueados",
      "Sin Anuncios"
    ],
    "timestamp": 1776894007249,
    "order": 17,
    "visits": 1,
    "warningVisible": false,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "UWiGr3eqIn4akkc2r6Va",
    "name": "Grand Truck Simulator 2",
    "description": "La segunda edición de la saga Grand Truck Simulator trae un nuevo concepto en simulación de logística para móviles.\nAhora más que nunca debes cuidar tu flota de vehículos.",
    "ver": "V1.0.7F7",
    "size": "170 MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/ed9ty5v8tottlx7/Grand_Truck_Simulator_2_v1.0.7f7_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/ed9ty5v8tottlx7/Grand_Truck_Simulator_2_v1.0.7f7_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Diamantes Infinitos",
      "Nivel XP 999",
      "Licencia E",
      "Sin Anuncios",
      "Compras Gratis"
    ],
    "timestamp": 1776894000644,
    "order": 16,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "Xt9xo2LPD5ZDaKE3eteV",
    "name": "Bus Simulator Indonesia",
    "description": "Bus Simulator Indonesia (también conocido como BUSSID) te permitirá experimentar la experiencia de ser conductor de autobús en Indonesia de una forma divertida y auténtica. ",
    "ver": "V4. 4.1",
    "size": "550MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/k8t4aipdp5b8610/Bus_Simulator_Indonesia_v4.4.1_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/k8t4aipdp5b8610/Bus_Simulator_Indonesia_v4.4.1_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Velocidad Speed",
      "Sin Anuncios",
      "Tanque full"
    ],
    "timestamp": 1776893987917,
    "order": 15,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "JRGS4BVGevTx2V5txgzV",
    "name": "World Bus Driving Simulator",
    "description": "Conduce los autobuses más famosos de Brasil y del mundo por desafiantes carreteras que pondrán a prueba tus habilidades como conductor. ¡Siéntete como un conductor de autobús!",
    "ver": "V1. 394",
    "size": "800 MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/k020lx7zuw2m7j8/World_Bus_Driving_Simulator_v1.394_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/k020lx7zuw2m7j8/World_Bus_Driving_Simulator_v1.394_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero infinito",
      "Buses paga Liberados",
      "Todos los autobuses Nivel 10 desbloqueados",
      "Nivel XP 50",
      "Todo el Garaje liberado",
      "Sin Anuncios"
    ],
    "timestamp": 1776893647166,
    "order": 14,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "VhQbTpgCbpKD3d8lKIh5",
    "name": "World Truck Driving Simulator",
    "description": "Conduce los camiones más famosos del mundo por desafiantes carreteras que pondrán a prueba tus habilidades al volante. ¡Siente la vida de un camionero!",
    "ver": "V1. 424",
    "size": "1.1 GB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/tpxt07b0kr5ofzb/World_Truck_Driving_v1.424_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/tpxt07b0kr5ofzb/World_Truck_Driving_v1.424_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Nivel XP 30",
      "Camiones VIP Liberados",
      "Camiones Nivel 10 liberados",
      "Sin Anuncios"
    ],
    "timestamp": 1776893640738,
    "order": 13,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "DSlBr0MMnQUHIqEKuUPz",
    "name": "Car Simulator 2",
    "description": "¡Juega al simulador de conducción más realista de 2026! ¡Descubre nuevo mundo abierto, más de 100 coches y una jugabilidad excelente!",
    "ver": "V1. 60.6",
    "size": "700MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/u95mziakegzh418/Car_Simulator_2_v1.60.2_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/u95mziakegzh418/Car_Simulator_2_v1.60.2_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Tokens Infinito",
      "Todos los coches liberados",
      "Garages Liberados",
      "Mansiones desbloqueados",
      "Sirenas",
      "compras gratis",
      "Sin Anuncios"
    ],
    "timestamp": 1776893633467,
    "order": 12,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "IM35lDbfpmOvxzQFxOfm",
    "name": "Rally Fury",
    "description": "¡Experimenta la emoción y el desafío de las carreras de rally de alta velocidad! Pon a prueba tus habilidades de conducción en pruebas de tiempo, compite contra oponentes desafiantes y compite en eventos especiales de desafío.",
    "ver": "V1. 121",
    "size": "187 MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/wm1eogslkj0vaal/Rally_Fury_v1.121_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/wm1eogslkj0vaal/Rally_Fury_v1.121_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Tokens Infinito",
      "Online Multiplayer",
      "Sin Anuncios"
    ],
    "timestamp": 1776893624439,
    "order": 11,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "1",
    "name": "Global Truck Online",
    "description": "Este juego fue desarrollado por JoelDroid Labs y modificado para ofrecer la mejor experiencia premium. Vive el simulador de camiones más avanzado con multijugador masivo.",
    "ver": "v0.0.96",
    "size": "740 MB",
    "visible": true,
    "modBadgeText": "MOD APP",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/pl1aui3qxvstwhe/Global_Truck_Online_v0.0.96_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/pl1aui3qxvstwhe/Global_Truck_Online_v0.0.96_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Monedas Infinitas",
      "Sin Anuncios",
      "Todo Desbloqueado"
    ],
    "timestamp": 1776893359022,
    "order": 9,
    "visits": 1250,
    "warningVisible": true,
    "warningText": "Si el juego presenta problemas al instalar, asegúrate de desinstalar cualquier versión previa de la Google Play Store para evitar conflictos.",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "2",
    "name": "Trucker of Europe 3",
    "description": "Una obra maestra de la conducción pesada. Modificado especialmente para entusiastas que buscan desbloquear todo el potencial de la gestión de carga.",
    "ver": "v0.7.64",
    "size": "605 MB",
    "visible": true,
    "modBadgeText": "MOD APP",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/292kmy6h9mqevaf/Truckers_of_Europe_3_v0.7.64_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/292kmy6h9mqevaf/Truckers_of_Europe_3_v0.7.64_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Monedas Infinitas",
      "XP nivel 9999",
      "Eres legendario",
      "Sin Anuncios",
      "Sin Virus"
    ],
    "timestamp": 1776893338767,
    "order": 7,
    "visits": 890,
    "warningVisible": true,
    "warningText": "Si el juego presenta problemas al instalar, asegúrate de desinstalar cualquier versión previa de la Google Play Store para evitar conflictos.",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "6Cl6XJzYJVTVfoum82Tu",
    "name": "Subway Surfers",
    "description": "¡CORRE tan rápido como puedas!\n¡ESQUIVA los trenes que vienen hacia ti! \nAyuda a Jake, Tricky y Fresh a escapar del inspector gruñón y su perro. \n",
    "ver": "V3.61.1",
    "size": "220 MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/p241wfhn6h17eul/Subway_Surfers_v3.61.1_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/p241wfhn6h17eul/Subway_Surfers_v3.61.1_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Monedas Infinitos",
      "Llaves Infinitos",
      "Aerotablas infinito",
      "Multijugador online",
      "Personajes liberados",
      "Skins liberados"
    ],
    "timestamp": 1776893157357,
    "order": 8,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "BoNn6QyU5GHvEXWthbsy",
    "name": "Hill Climb Racing ",
    "description": "¡Ábrete paso por la colina en este juego de carreras basado en la física! ¡Puedes jugar sin conexión!\nConoce a Bill, el joven aspirante a piloto de colinas. Está a punto de embarcarse en un viaje que lo llevará a donde ningún piloto ha llegado antes. Con poco respeto por las leyes de la física, Bill no descansará hasta que haya conquistado las colinas más altas.",
    "ver": "V1.68.1",
    "size": "119 MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD (Opción 1)",
    "downloadButtonLink1": "https://www.mediafire.com/file/7zefg7z39q88vgs/Hill_Climb_Racing_v1.68.1_%255BMOD%255D.apk/file",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD (Opción 2)",
    "downloadButtonLink2": "https://www.mediafire.com/file/7zefg7z39q88vgs/Hill_Climb_Racing_v1.68.1_%255BMOD%255D.apk/file",
    "downloadButtonVisible2": true,
    "features": [
      "Monedas Infinitos",
      "Diamantes Infinitos",
      "Gasolina infinito",
      "Todo liberado"
    ],
    "timestamp": 1776893150458,
    "order": 8,
    "visits": 0,
    "warningVisible": true,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  },
  {
    "id": "GsL7ow00nHxijoDVMkWe",
    "name": "Universal Truck Simulator ",
    "description": "Universal Truck Simulator ofrece una experiencia de simulación de \nconducción real a los jugadores móviles, un juego con comentarios \nconstantes de todo el mundo de los camiones.",
    "ver": "V2.3.1",
    "size": "100MB",
    "visible": true,
    "modBadgeText": "MOD APK",
    "modBadgeBgColor": "#ef4444",
    "modBadgeVisible": true,
    "updateBadgeText": "UPDATE",
    "updateBadgeVisible": true,
    "updateBadgeBgColor": "#10b981",
    "homeButtonVisible": true,
    "downloadButtonText1": "DESCARGAR MOD 1",
    "downloadButtonLink1": "",
    "downloadButtonVisible1": true,
    "downloadButtonText2": "DESCARGAR MOD 2",
    "downloadButtonLink2": "",
    "downloadButtonVisible2": true,
    "features": [
      "Dinero Infinito",
      "Nivel XP 70",
      "Mapas liberados",
      "Sin Anuncios"
    ],
    "timestamp": 0,
    "order": 18,
    "visits": 0,
    "warningVisible": false,
    "warningText": "",
    "youtubeUrl": "",
    "installYoutubeUrl": "",
    "dlPageName1": "",
    "dlPageVer1": "",
    "dlPageSize1": "",
    "dlPageBtn1": "",
    "dlPageName2": "",
    "dlPageVer2": "",
    "dlPageSize2": "",
    "dlPageBtn2": ""
  }
];

/* ── THUMBS: se guardan en localStorage para 0ms en visitas siguientes ── */
/* Se cargan en background en la primera visita desde el Gist               */
const JUEGOS_THUMBS_GIST = 'https://gist.githubusercontent.com/JoelDroidModsYT/5981d391897fe461dc5ac9ba7303b8f2/raw/games.json';

/* ── API de sincronización con el index.html ─────────────────────────── */
/* Exponer para que el index.html pueda leerlo antes de que DOMContentLoaded */
window.JUEGOS_DATA          = JUEGOS_DATA;
window.__JD_DATA_READY      = true;
window.__JD_DATA_VERSION    = '20260423012204';
